### ISSUE TITLE
Animations do not detect delay w/ stagger

### ISSUE THREAD

**Issue by dennisregalado** [mystroken/g#1]
Hi there,

Staggered animations do not seem to work using ` delay: index => (index + 1) * 1000,
`

When trying to stagger multiple elements with:

`const h1txt = new Animate({
      el: ".title",
      d: 1200,
      p: { y: [100, 0] },
      e: "io4", 
      delay: index => (index + 1) * 1000
    });
    h1txt.play();`

**Comment by mystroken** [comment]
Indeed!
I was still working on this feature.

And I am happy now to announce you that with ```v0.0.6``` you can now stagger **delay** and **duration** ^^
