### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by ishigo1987** [mystroken/g#2]
Good work but if i can tell something about your work
1) Too much code you can try to refactoring your code
2) It will be nice if you can implement some event like  animation.addEventListener('finish',myFunction) or better, use promise api

**Comment by mystroken** [comment]
Hello @ishigo1987 ^_^

I really appreciate your interest for this project :-)
About your suggestions:

1. ```Too much code you can try to refactoring your code```: which part of the code for example. Are you talking about the whole project? Or about a specific function? This could help me figuring out where is the bottleneck.
2. About the finish event listener: I guess you're talking about the Animate.js file. Indeed you can pass a callback that will be called at the end of the animation ;-)

```javascript
new Animate({
  el: 'span',
  d: 1000,
  p: { y: [100, 0] },
  cb: () => console.log('The animation is ended !'),
})
```
NOTE: I am just figuring out that I've not mentioned that in the doc. Thanks for your intervention.

**Comment by ishigo1987** [comment]
1) I'm talking about the whole project,we can talk more about that this night
2) Ok copy
